---
# Staging Inventory for VPN Infrastructure Testing
# Consolidated from planet-proxy-devops-controller and the-deployment

all:
  children:
    vpn_servers:
      children:
        staging_wireguard:
          hosts:
            staging-wg-001:
              ansible_host: "192.168.1.100"
              vpn_region: "staging"
              vpn_protocol: "wireguard"
              server_role: "wireguard_server"
            staging-wg-002:
              ansible_host: "192.168.1.101"
              vpn_region: "staging"
              vpn_protocol: "wireguard"
              server_role: "wireguard_server"
        
        staging_openvpn:
          hosts:
            staging-ovpn-001:
              ansible_host: "192.168.1.110"
              vpn_region: "staging"
              vpn_protocol: "openvpn"
              server_role: "openvpn_server"
        
        staging_monitoring:
          hosts:
            staging-monitor-001:
              ansible_host: "192.168.1.120"
              vpn_region: "staging"
              server_role: "monitoring_server"

  vars:
    # Staging environment variables
    environment_type: "staging"
    deployment_mode: "testing"
    
    # SSH Configuration for staging
    ansible_user: "ansible"
    ansible_ssh_private_key_file: "~/.ssh/ansible_ed25519"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    
    # Staging-specific settings
    monitoring_enabled: true
    security_hardening: false  # Disabled for easier testing
    vault_integration: false   # Simplified for staging
    
    # Performance settings for staging
    max_parallel_deployments: 5
    deployment_timeout: 300