---
# Production VPN Infrastructure Inventory
# 30 servers across 3 geographic regions
# Updated: 2025-01-05

all:
  children:
    vpn_servers:
      children:
        # Europe Region - 12 servers
        europe:
          hosts:
            eu-wg-001:
              ansible_host: 185.199.108.153
              vpn_region: europe
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Frankfurt, Germany"
            eu-wg-002:
              ansible_host: 185.199.109.154
              vpn_region: europe
              vpn_protocols: [wireguard, openvpn]
              server_location: "Amsterdam, Netherlands"
            eu-wg-003:
              ansible_host: 185.199.110.155
              vpn_region: europe
              vpn_protocols: [wireguard, amneziawg]
              server_location: "London, UK"
            eu-wg-004:
              ansible_host: 185.199.111.156
              vpn_region: europe
              vpn_protocols: [openvpn]
              server_location: "Paris, France"
            eu-wg-005:
              ansible_host: 185.199.112.157
              vpn_region: europe
              vpn_protocols: [wireguard, openvpn]
              server_location: "Milan, Italy"
            eu-wg-006:
              ansible_host: 185.199.113.158
              vpn_region: europe
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Madrid, Spain"
            eu-wg-007:
              ansible_host: 185.199.114.159
              vpn_region: europe
              vpn_protocols: [wireguard, openvpn]
              server_location: "Stockholm, Sweden"
            eu-wg-008:
              ansible_host: 185.199.115.160
              vpn_region: europe
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Warsaw, Poland"
            eu-wg-009:
              ansible_host: 185.199.116.161
              vpn_region: europe
              vpn_protocols: [openvpn]
              server_location: "Prague, Czech Republic"
            eu-wg-010:
              ansible_host: 185.199.117.162
              vpn_region: europe
              vpn_protocols: [wireguard, openvpn]
              server_location: "Vienna, Austria"
            eu-wg-011:
              ansible_host: 185.199.118.163
              vpn_region: europe
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Zurich, Switzerland"
            eu-wg-012:
              ansible_host: 185.199.119.164
              vpn_region: europe
              vpn_protocols: [wireguard, openvpn]
              server_location: "Helsinki, Finland"

        # North America Region - 10 servers
        north_america:
          hosts:
            na-wg-001:
              ansible_host: 192.241.128.100
              vpn_region: north_america
              vpn_protocols: [wireguard, amneziawg]
              server_location: "New York, USA"
            na-wg-002:
              ansible_host: 192.241.129.101
              vpn_region: north_america
              vpn_protocols: [wireguard, openvpn]
              server_location: "Los Angeles, USA"
            na-wg-003:
              ansible_host: 192.241.130.102
              vpn_region: north_america
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Chicago, USA"
            na-wg-004:
              ansible_host: 192.241.131.103
              vpn_region: north_america
              vpn_protocols: [openvpn]
              server_location: "Dallas, USA"
            na-wg-005:
              ansible_host: 192.241.132.104
              vpn_region: north_america
              vpn_protocols: [wireguard, openvpn]
              server_location: "Miami, USA"
            na-wg-006:
              ansible_host: 192.241.133.105
              vpn_region: north_america
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Seattle, USA"
            na-wg-007:
              ansible_host: 192.241.134.106
              vpn_region: north_america
              vpn_protocols: [wireguard, openvpn]
              server_location: "Toronto, Canada"
            na-wg-008:
              ansible_host: 192.241.135.107
              vpn_region: north_america
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Vancouver, Canada"
            na-wg-009:
              ansible_host: 192.241.136.108
              vpn_region: north_america
              vpn_protocols: [openvpn]
              server_location: "Atlanta, USA"
            na-wg-010:
              ansible_host: 192.241.137.109
              vpn_region: north_america
              vpn_protocols: [wireguard, openvpn]
              server_location: "Denver, USA"

        # Asia Pacific Region - 8 servers
        asia_pacific:
          hosts:
            ap-wg-001:
              ansible_host: 203.175.10.200
              vpn_region: asia_pacific
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Tokyo, Japan"
            ap-wg-002:
              ansible_host: 203.175.11.201
              vpn_region: asia_pacific
              vpn_protocols: [wireguard, openvpn]
              server_location: "Singapore"
            ap-wg-003:
              ansible_host: 203.175.12.202
              vpn_region: asia_pacific
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Hong Kong"
            ap-wg-004:
              ansible_host: 203.175.13.203
              vpn_region: asia_pacific
              vpn_protocols: [openvpn]
              server_location: "Sydney, Australia"
            ap-wg-005:
              ansible_host: 203.175.14.204
              vpn_region: asia_pacific
              vpn_protocols: [wireguard, openvpn]
              server_location: "Seoul, South Korea"
            ap-wg-006:
              ansible_host: 203.175.15.205
              vpn_region: asia_pacific
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Mumbai, India"
            ap-wg-007:
              ansible_host: 203.175.16.206
              vpn_region: asia_pacific
              vpn_protocols: [wireguard, openvpn]
              server_location: "Bangkok, Thailand"
            ap-wg-008:
              ansible_host: 203.175.17.207
              vpn_region: asia_pacific
              vpn_protocols: [wireguard, amneziawg]
              server_location: "Manila, Philippines"

    # Protocol-specific groups
    wireguard_servers:
      hosts:
        # Europe WireGuard servers
        eu-wg-001:
        eu-wg-002:
        eu-wg-003:
        eu-wg-005:
        eu-wg-006:
        eu-wg-007:
        eu-wg-008:
        eu-wg-010:
        eu-wg-011:
        eu-wg-012:
        # North America WireGuard servers
        na-wg-001:
        na-wg-002:
        na-wg-003:
        na-wg-005:
        na-wg-006:
        na-wg-007:
        na-wg-008:
        na-wg-010:
        # Asia Pacific WireGuard servers
        ap-wg-001:
        ap-wg-002:
        ap-wg-003:
        ap-wg-005:
        ap-wg-006:
        ap-wg-007:
        ap-wg-008:

    amneziawg_servers:
      hosts:
        # Europe AmneziaWG servers
        eu-wg-001:
        eu-wg-003:
        eu-wg-006:
        eu-wg-008:
        eu-wg-011:
        # North America AmneziaWG servers
        na-wg-001:
        na-wg-003:
        na-wg-006:
        na-wg-008:
        # Asia Pacific AmneziaWG servers
        ap-wg-001:
        ap-wg-003:
        ap-wg-006:
        ap-wg-008:

    openvpn_servers:
      hosts:
        # Europe OpenVPN servers
        eu-wg-002:
        eu-wg-004:
        eu-wg-005:
        eu-wg-007:
        eu-wg-009:
        eu-wg-010:
        eu-wg-012:
        # North America OpenVPN servers
        na-wg-002:
        na-wg-004:
        na-wg-005:
        na-wg-007:
        na-wg-009:
        na-wg-010:
        # Asia Pacific OpenVPN servers
        ap-wg-002:
        ap-wg-004:
        ap-wg-005:
        ap-wg-007:

  vars:
    # Global variables for all servers
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/ansible_ed25519
    ansible_become: yes
    ansible_become_method: sudo
    
    # VPN Infrastructure settings
    vpn_infrastructure_version: "2.0.0"
    deployment_environment: "production"
    monitoring_enabled: true
    security_hardening_enabled: true
    
    # Common ports
    ssh_port: 22
    wireguard_port: 51820
    amneziawg_port: 51821
    openvpn_udp_port: 1194
    openvpn_tcp_port: 443
    wg_dashboard_port: 10086
    
    # Monitoring ports
    node_exporter_port: 9100
    wg_exporter_port: 9586
    openvpn_exporter_port: 9176
    
    # DNS settings
    coredns_port: 53
    dns_upstream_servers:
      - "1.1.1.1"
      - "8.8.8.8"
      - "9.9.9.9"